# Generated by Django 4.2.29 on 2026-03-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0002_alter_medizinischedaten_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medizinischedaten',
            name='medikamende',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Notfallkontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beziehung', models.CharField(max_length=50)),
                ('handynummer', models.CharField(max_length=20)),
                ('mitarbeiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notfallkontakt', to='mitarbeiter.mitarbeiter')),
            ],
        ),
    ]
