# Generated by Django 4.2.29 on 2026-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0003_medizinischedaten_medikamende_notfallkontakt'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfallkontakt',
            name='beziehung_andere',
            field=models.CharField(blank=True, help_text="Nur bei 'Andere' ausfüllen", max_length=100),
        ),
        migrations.AlterField(
            model_name='notfallkontakt',
            name='beziehung',
            field=models.CharField(choices=[('elternteil', 'Elternteil'), ('ehepartner', 'Ehepartner/in'), ('kind', 'Kind'), ('geschwister', 'Geschwister'), ('freund', 'Freund/in'), ('andere', 'Andere')], default='andere', max_length=20),
        ),
    ]
