# Generated by Django 4.2.29 on 2026-03-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0004_notfallkontakt_beziehung_andere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifikation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MitarbeiterQualifikation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_erworben', models.DateField()),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitarbeiter.mitarbeiter')),
                ('qualifikation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitarbeiter.qualifikation')),
            ],
            options={
                'unique_together': {('mitarbeiter', 'qualifikation')},
            },
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='qualifikationen',
            field=models.ManyToManyField(through='mitarbeiter.MitarbeiterQualifikation', to='mitarbeiter.qualifikation'),
        ),
    ]
