# Generated by Django 4.2.29 on 2026-03-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0005_qualifikation_mitarbeiterqualifikation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medizinischedaten',
            name='blutgruppe',
        ),
        migrations.AddField(
            model_name='medizinischedaten',
            name='beziehung',
            field=models.CharField(choices=[('0+', '0+'), ('0-', '0-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='--', max_length=3),
        ),
    ]
