# Generated by Django 4.2.29 on 2026-03-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0006_remove_medizinischedaten_blutgruppe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medizinischedaten',
            old_name='beziehung',
            new_name='blutgruppe',
        ),
    ]
