# Generated by Django 4.2.29 on 2026-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0007_rename_beziehung_medizinischedaten_blutgruppe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medizinischedaten',
            name='blutgruppe',
            field=models.CharField(choices=[('--', '--'), ('0+', '0+'), ('0-', '0-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='--', max_length=3),
        ),
    ]
