# Generated by Django 4.2.29 on 2026-03-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0008_alter_medizinischedaten_blutgruppe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalnummer', models.CharField(max_length=50, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('geburtsdatum', models.DateField()),
                ('familienstand', models.CharField(choices=[('--', '--'), ('ledig', 'Ledig'), ('verheiratet', 'Verheiratet'), ('geschieden', 'Geschieden'), ('verwitwet', 'Verwitwet')], default='--', max_length=20)),
                ('kinder', models.IntegerField(default=0)),
                ('kotonnummer', models.CharField(blank=True, max_length=50)),
                ('mitarbeiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_daten', to='mitarbeiter.mitarbeiter')),
            ],
        ),
    ]
