# Generated by Django 4.2.29 on 2026-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0009_privatedaten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedaten',
            name='adresse',
        ),
        migrations.AddField(
            model_name='privatedaten',
            name='hausnummer',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='privatedaten',
            name='land',
            field=models.CharField(default='Deutschland', max_length=100),
        ),
        migrations.AddField(
            model_name='privatedaten',
            name='ort',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AddField(
            model_name='privatedaten',
            name='plz',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='privatedaten',
            name='strasse',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='privatedaten',
            name='kinder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
