# Generated by Django 4.2.29 on 2026-03-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0010_remove_privatedaten_adresse_privatedaten_hausnummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiterqualifikation',
            name='ablaufdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notfallkontakt',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notfallkontakt', to='mitarbeiter.mitarbeiter'),
        ),
    ]
