# Generated by Django 4.2.29 on 2026-03-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0011_mitarbeiterqualifikation_ablaufdatum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitarbeiter',
            options={'verbose_name_plural': 'Mitarbeiter'},
        ),
        migrations.AlterModelOptions(
            name='qualifikation',
            options={'verbose_name_plural': 'Qualifikationen'},
        ),
    ]
