# Generated by Django 4.2.29 on 2026-03-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0012_alter_mitarbeiter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medizinischedaten',
            options={'verbose_name_plural': 'Medizinische Daten'},
        ),
        migrations.AlterModelOptions(
            name='mitarbeiterqualifikation',
            options={'verbose_name_plural': 'Mitarbeiter-Qualifikationen'},
        ),
        migrations.AlterModelOptions(
            name='notfallkontakt',
            options={'verbose_name_plural': 'Notfallkontakte'},
        ),
        migrations.AlterModelOptions(
            name='privatedaten',
            options={'verbose_name_plural': 'Private Daten'},
        ),
    ]
