# Generated by Django 4.2.29 on 2026-09-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrzeuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Fahrzeuge',
            },
        ),
        migrations.CreateModel(
            name='Geraete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Geräte',
            },
        ),
    ]
