# Generated by Django 4.2.29 on 2026-09-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrzeuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Fahrzeuge',
            },
        ),
        migrations.CreateModel(
            name='Geraete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Geräte',
            },
        ),
        migrations.CreateModel(
            name='Mangel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurzbeschreibung', models.TextField(verbose_name='Kurzbeschreibung (Freitext)')),
                ('mangelbeschreibung', models.TextField(verbose_name='Mangelbeschreibung (Freitext)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maengelmelder.fahrzeuge', verbose_name='Fahrzeug')),
                ('geraet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maengelmelder.geraete', verbose_name='Gerät')),
            ],
            options={
                'verbose_name': 'Mangel',
                'verbose_name_plural': 'Mängel',
            },
        ),
    ]
