# Generated by Django 4.2.29 on 2026-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maengelmelder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrzeuge',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (Freitext)'),
        ),
        migrations.AddField(
            model_name='geraete',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (Freitext)'),
        ),
    ]
