# Generated by Django 4.2.29 on 2026-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maengelmelder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurzbeschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Kurzbeschreibungen',
            },
        ),
        migrations.CreateModel(
            name='Mangelbeschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Mangelbeschreibungen',
            },
        ),
    ]
